apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: python-app-rules
  labels:
    release: prometheus-stack         # שוב: חייב להתאים לשם ההלם-ריליס
spec:
  groups:
    - name: python-app.rules
      rules:
        - alert: PythonAppHighRestarts
          expr: increase(kube_pod_container_status_restarts_total{namespace="default", pod=~"python-app-deployment-.*"}[5m]) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Python app is restarting too often"
            description: "Pod {{ $labels.pod }} restarted more than once in the last 5 minutes."
