apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-servicemonitor
  labels:
    release: prometheus-stack   # חשוב! חייב להתאים ל-Helm release של kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: python-app           # חייב להתאים ל-label של ה-Service (python-app-service)
  namespaceSelector:
    matchNames:
      - default                 # ה-namespace שבו ה-Service שלך רץ
  endpoints:
    - port: http                # שם הפורט מה-Service (port.name)
      path: /metrics            # איפה שהאפליקציה חושפת metrics
      interval: 15s
