# devops_app/argocd/nginx-helm/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 18.2.6   # example: set a real current version
    helm:
      # Raw YAML string of values for the chart
      values: |
        replicaCount: 2
        service:
          type: ClusterIP
        containerPorts:
          http: 8080
        image:
          registry: docker.io
          repository: bitnami/nginx
          tag: 1.27.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
